config/routes.rb
WatchWithMe::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  resources :authentications
  
  resources :movies
  resources :users, :only => :show do
    resources :reservations, :only => [:show, :index]
  end
  resources :tickets, :only => [:create, :destroy]
  resources :reservations, :only => [:new, :create, :edit, :update]
  

  
  root :to => "info#main"
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :organizer, :class_name => "User"
  belongs_to :movie
  has_many :tickets,
    :order => "participant_id DESC"#,
#    :dependent => :destroy
  has_many :participants, :class_name => "User", :source => :participant, :through => :tickets
  
  delegate :title, :to => :movie
  
  accepts_nested_attributes_for :tickets, :allow_destroy => true
  
  validates_presence_of :reserved_at, :on => :create, :message => "can't be blank, must take place some time"
  validates_presence_of :movie, :on => :create, :message => "can't be blank"
  
  scope :upcoming, lambda { where("reserved_at > ?", Time.now)}
  scope :recent, lambda { |time_ago = 4.week.ago| where(:reserved_at => time_ago..Time.now ) }
  scope :visible, where("visible_for_public = ?", true)
  
  
  def visible_for
    visible_for_public ? "everybody" : "participants only"
  end
  
  def visible_for_user?(user)
    if visible_for_public
      return true
    else
      participants.include?(user) || user == organizer
    end
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :find_user, :only => [:show]
  before_filter :authenticate_user!, :except => [:show]
  
  def show
    @reservation = Reservation.find(params[:id], :include => [:participants, :organizer,:movie])
    if @reservation.visible_for_user?(current_user)
      @tickets = @reservation.tickets
      @organizer = @reservation.organizer
    else
      redirect_to @user
    end
    
    
  end

  def index
    if user_signed_in?
      @participated_reservations = current_user.participated_reservations.all(:joins => [:tickets,:movie], :select => ["reservations.*, count(DISTINCT tickets.id) as tickets_count","reservations.*, movies.title as movie_title"],:group => "reservations.id")
      @organized_reservations = current_user.organized_reservations.all(:joins => [:tickets,:movie], :select => ["reservations.*, count(DISTINCT tickets.id) as tickets_count","reservations.*, movies.title as movie_title"],:group => "reservations.id")
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @reservation = current_user.organized_reservations.new
    @reservation.visible_for_public = true
  end
  
  def create
    ticket_count = params[:ticket_count].to_i
    @reservation = current_user.organized_reservations.new(params[:reservation])
    if @reservation.save  
      ticket_count.times { @reservation.tickets.create }
      redirect_to([current_user,@reservation], :notice => "Reservations successfully created.")
    else
      render :action => :new
    end
  end

  def edit
    @reservation = current_user.organized_reservations.find(params[:id])
  end
  
  def update
    @reservation = current_user.organized_reservations.find(params[:id])
    if @reservation.update_attributes(params[:reservation])
      flash[:notice] = "Successfully updated exercise."
       redirect_to([current_user,@reservation], :notice => "Reservations successfully changed.")
    else
      render :action => 'edit'
    end
  end

  def destroy
  end
  
  private
  
  def find_user
    @user = User.find_user_by_url(params[:user_id])
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_reservations_list.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Reserved for</th>
		<th>@</th>
    <th>Tickets</th>
		<th>Visible</th>
  </tr>
  <% for reservation in reservations %>
    <tr>
      <td><%= link_to reservation.movie_title, [current_user,reservation] %></td>
      <td><%= reservation.reserved_at.to_s(:long) %></td>
			<td><%= reservation.cinema_room %></td>
      <td><%= pluralize reservation.tickets_count, "ticket" %></td>
			<td><%= reservation.visible_for %></td>
      <% if reservation.organizer == current_user %>
				<td><%= link_to "Show", [current_user,reservation] %></td>
	      <td><%= link_to "Edit", edit_reservation_path(reservation) %></td>
	      <td><%= link_to "Destroy", [current_user,reservation], :confirm => 'Are you sure?', :method => :delete %></td>
			<% end %>
    </tr>
  <% end %>
</table>

app/views/reservations/_ticket_fields.html.erb
<li class="fields">
	<div id="reserved">
		<%= f.collection_select(:participant_id, User.all, :id, :username, :include_blank => true) %>
		<%= link_to_remove_fields("remove",f) %>
	</div>
</li>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Edit the reservation <%= link_to @reservation.movie.title, @reservation.movie %></h1>


<%= form_for [@reservation] do |f| %>
	<div class="field">
		<%= f.label :visible_for_public %><br>
		<%= f.check_box :visible_for_public, %>
	</div>
	<h2 class="grid_4">Tickets:</h2>
	<ul class="ticket-list grid_6">
		<%= f.fields_for :tickets do |builder| %>
			<%= render "ticket_fields", :f => builder %>
		<% end %>
		<%= link_to_add_fields("Add Ticket", f, :tickets) %><br />
	</ul>
	<%= f.submit %>
<% end %>

app/views/reservations/index.html.erb
<h1>My Reservations</h1>

<div id="new-reservation">
	<h3><%= link_to "New Reservation", new_reservation_path %>
</div>
<div class="reservations-list", id="participated-reservations">
	<h2>My participated reservations</h2>
	<%= render "reservations_list", :reservations=> @participated_reservations %>
</div>
<div class="reservations-list", id="organized-reservations">
	<h2>My organized reservations</h2>
	<%= render "reservations_list", :reservations=> @organized_reservations %>
</div>

app/views/reservations/new.html.erb
<h2>Add new reservation</h2>
<%= form_for @reservation do |f| %>
	<div class="field">
		<%= f.label :movie %><br>
		<%= f.collection_select(:movie_id, Movie.all, :id, :title) %>
  </div>
	<div class="field">
		<%= f.label :reserved_at %><br>
		<%= f.datetime_select :reserved_at , :discard_year => true, :minute_step => 5%>
	</div>
	<div class="field">
		<%= f.label :meeting_at%><br>
		<%= f.time_select :meeting_at, :discard_year => true, :minute_step => 5%><br>
	</div>
	<div class="field">
		<%= f.label :visible_for_public, "Public" %><br>
		<%= f.check_box :visible_for_public %>
	</div>
	<div class="field">
		<%= f.label :tickets %><br>
		<%= select_tag(:ticket_count, options_for_select(%w{ 1 2 3 4 5 6 7 8 9 10 },6)) %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/show.html.erb
<div id="reservation-details">
	<div id="movie_image" class="grid_3">
		<%= image_tag "http://lorempixum.com/g/214/317/" %>
	</div>
	<div id="description" class="grid_6 prefix_1">
		<p>
			Watch<br>
			<span class="infos" id="movie-title"><%= @reservation.title %></span><br>
			with <span class="infos"><%= @organizer.username %></span>
			<% if @organizer == current_user %>
				(<%= link_to "edit", edit_reservation_path %>) 
			<% end %>
		</p>
		<p>
			on <span class="infos"><%= @reservation.reserved_at.strftime '%A, %b %e, %Y - %H:%M' %></span>
		</p>
		<p>
			at <span class="infos">Cinema </span>
		</p>		
	</div>
</div>
<div class="clearfix"></div>
<div id="tickets">
	<h2 class="grid_4">Tickets:</h2>
	<ul class="ticket-list grid_6">
		<% for ticket in @reservation.tickets.reserved %>
			<li id="reserved">
				<% if ticket.participant %>
					<span class="username grid_2">
						<%= link_to ticket.participant.username, ticket.participant %> 
					</span>
					
					<% if current_user == ticket.participant %>
						<span id="delete-ticket-button"><%= link_to "delete me", ticket, :method => :delete %></span>
					<% end %>
				<% end %>
			</li>
		<% end %>
		<% unless @reservation.tickets.free.empty? %>
			<li id="free">
				<span class="username grid_2">
					-- ??? --
				</span>
				<span id="create-ticket-button">
					<%= link_to "count me in", tickets_path(:ticket_id => @reservation.tickets.free.first), :action => "create", :controller => "tickets", :method => :post %>
				</span>
				<span id="batch">
					<%= @reservation.tickets.free.count %> left
				</span>
			</li>
		<% end %>
	</ul>
</div>