config/routes.rb
WatchWithMe::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  resources :authentications
  
  resources :movies
  resources :users, :only => :show do
    resources :reservations, :only => [:show, :index]
  end
  resources :tickets, :only => [:create, :destroy]
  resources :reservations, :only => [:new, :create, :edit, :update]
  

  
  root :to => "info#main"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WatchWithMe</title>
  <%= stylesheet_link_tag :all, :cache => true %>
	<!-- <%= javascript_include_tag 'jquery-1.6.1.js', 'jquery.rails.js', :cache => true %> -->
	<%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<header>
		<div id="top-bar" class="container_12">
			<div class="prefix_1 suffix_1">
				<div id="dropdown-outer">
					<div id="notifications" class="grid_6">
						<% if flash[:notice] %>
							<p class="notice"><%= flash[:notice] %></p>
						<% end %>
						<% if flash[:error] %>
							<p class="error"><%= flash[:error] %></p>
						<% end %>
					</div>
					<div id="userpanel" class="grid_4">
						<% if user_signed_in? %>
							<div id="username">
								<%= link_to current_user.username, current_user %> <%= link_to_function("▾","dropdown()") %>
							</div>
							<div class="dropdown">
								<ul>
									<li><%= link_to "Home", root_path %></li>
									<li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
									<li><%= link_to "My reservations", user_reservations_path(current_user) %></li>
									<li><%= link_to "Sign out", destroy_user_session_path %></li>
								</ul>
							</div>
						<% else %>
							<div id="not-signed-in">
								<%= link_to 'Sign in', new_user_session_path %> | <%= link_to "Sign up a new account", new_user_registration_path %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</header>
	<div id="main" class="container_12 ">
		<div class="prefix_1 suffix_1">
			<%= yield %>
			<div class="clearfix"></div>
			<footer>
				<div id="footer-left" class="grid_5">
					This is where the left foot stands.
				</div>
				<div id="footer-right" class="grid_5">
					This is where the right foot stands.
				</div>
			</footer>
		</div>
	</div>

</body>
</html>